spring:
  jpa:
    show_sql: true
    hibernate:
      format_sql: false
      ddl-auto: update

# ----------------------------------------
# DataSources
# ----------------------------------------
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password